name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    - uses: actions/checkout@v1
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: bohregard/test-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
